services:
  mongo:
    image: mongo:7
    container_name: hadasim-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    secrets:
      - mongo_username
      - mongo_password

  server:
    image: hadasim-server
    container_name: hadasim-server
    ports:
      - "3500:3500"
    environment:
      PORT: 3500
    depends_on:
      - mongo
    secrets:
      - mongo_username
      - mongo_password

  client:
    image: hadasim-client
    container_name: hadasim-client
    ports:
      - "3000:80"
    depends_on:
      - server

secrets:
  mongo_username:
    file: ./secrets/mongo_username.txt
  mongo_password:
    file: ./secrets/mongo_password.txt

volumes:
  mongo_data: